# Generated by Django 4.1.1 on 2022-11-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnes', '0002_objets_personnes_commentaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnes',
            name='photo',
        ),
    ]
