# Generated by Django 4.0.4 on 2022-12-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnes', '0003_remove_personnes_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnes',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
